server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        ## REST-CLIENT -> http://localhost:8080/auth/login
        ## API-GATEWAY -> http://auth-service:4004/auth/login
        
        - id: auth-service-route
          uri: http://auth-service:4004
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ## REST CLIENT -> http://localhost:8080/api/patients
        ## API GATEWAY -> http://patient-service:4000/patients
        ## PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patient/**
          filters:
            - StripPrefix=1
            ## JWT VALIDATION using JwtValidationGatewayFilterFactory ie any request matching to predicates will be passed/go via to JwtValidationGatewayFilterFactory
            - JwtValidation

        ## REST-CLIENT -> http://localhost:8080/api-docs/patients
        ## API-GATEWAY -> http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patient
          filters:
            - RewritePath=/api-docs/patient,/v3/api-docs

#        - id: api-docs-auth-route
#          uri: http://auth-service:4005
#          predicates:
#            - Path=/api-docs/auth
#          filters:
#            - RewritePath=/api-docs/auth,/v3/api-docs