### POST request to create new patient
POST http://localhost:4000/patient
Content-Type: application/json

{
  "name": "John Doe Kafka Test Consumer",
  "email": "test12@consume.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}
###